version: "3.8"

services:
  pgsql:
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=buity
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=pawndarby

  redis:
    image: redis
    volumes:
      - redis_data:/data

  api:
    build: .
    ports:
      - 9000:9000
    environment:
      - DEBUG=True
      - TEST=False
      - SECRET_KEY=4981e57711ba3cc14bfaee9d7a8b2db4bafeed58d13a7a7aaaf873ba1e4a2ab1
      - DATABASE_URL=postgresql://postgres:pawndarby@pgsql/biuty
      - TEST_DATABASE_URL=postgresql://postgres:pawndarby@pgsql/biuty_test
      - REDIS_HOST=redis://redis
      - REDIS_DB=2
    depends_on:
      - pgsql
      - redis

volumes:
  postgres_data:
  redis_data:
