"""empty message

Revision ID: 1b8886f4312e
Revises: 
Create Date: 2021-11-06 01:02:37.545003

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "1b8886f4312e"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "provinces",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "cities",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("province", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["province"],
            ["provinces.id"],
            name="fk_cities_provinces_id_province",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("phone_number", sa.String(length=15), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("role", sa.SmallInteger(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=True),
        sa.Column("password", sa.String(length=255), nullable=False),
        sa.Column("date_joined", sa.DateTime(), nullable=True),
        sa.Column("card_number", sa.String(length=16), nullable=True),
        sa.Column("city", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["city"], ["cities.id"], name="fk_users_cities_id_city", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_table("cities")
    op.drop_table("provinces")
    # ### end Alembic commands ###
