"""empty message

Revision ID: 29946fa846ed
Revises: 6bfeb5cc9187
Create Date: 2021-11-06 09:59:06.302768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "29946fa846ed"
down_revision = "6bfeb5cc9187"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "users", ["phone_number"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "users", type_="unique")
    # ### end Alembic commands ###
