"""empty message

Revision ID: 57c6417bc80c
Revises: 29946fa846ed
Create Date: 2021-11-06 10:02:28.603656

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "57c6417bc80c"
down_revision = "29946fa846ed"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("store_count", sa.SmallInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "store_count")
    # ### end Alembic commands ###
