"""empty message

Revision ID: 6bfeb5cc9187
Revises: b4f4da8aef3c
Create Date: 2021-11-06 01:29:28.111593

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6bfeb5cc9187"
down_revision = "b4f4da8aef3c"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("stores_user_key", "stores", type_="unique")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint("stores_user_key", "stores", ["user"])
    # ### end Alembic commands ###
