"""empty message

Revision ID: 8eef84e750a3
Revises: 1b8886f4312e
Create Date: 2021-11-06 01:06:48.835056

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "8eef84e750a3"
down_revision = "1b8886f4312e"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_cities_id_city", "users", type_="foreignkey")
    op.drop_column("users", "city")
    op.drop_column("users", "card_number")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "card_number", sa.VARCHAR(length=16), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "users", sa.Column("city", sa.INTEGER(), autoincrement=False, nullable=True)
    )
    op.create_foreign_key(
        "fk_users_cities_id_city",
        "users",
        "cities",
        ["city"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
