"""empty message

Revision ID: b4f4da8aef3c
Revises: 8eef84e750a3
Create Date: 2021-11-06 01:28:02.541054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "b4f4da8aef3c"
down_revision = "8eef84e750a3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "stores",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("user", sa.BigInteger(), nullable=False),
        sa.Column("city", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("card_number", sa.String(length=16), nullable=False),
        sa.Column("address", sa.Text(), nullable=False),
        sa.Column("contact_number", sa.String(length=20), nullable=False),
        sa.Column("instagram", sa.String(length=30), nullable=True),
        sa.Column("telegram", sa.String(length=30), nullable=True),
        sa.ForeignKeyConstraint(
            ["city"], ["cities.id"], name="fk_stores_cities_id_city", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user"], ["users.id"], name="fk_stores_users_id_user", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("stores")
    # ### end Alembic commands ###
